version: "3"
services:
  nginx:
    container_name: nginx
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  flask:
    image: python:2.7
    build:
      context: python-flask-docker-hello-world
      dockerfile: Dockerfile-fl
    volumes:
      - "./:/app"
